export default function Home() {
  return (
    <main className="container">
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <div>
          <h1 className="text-gradient" style={{ fontSize: '2rem', marginBottom: '0.2rem' }}>Unified Operations Brain</h1>
          <p style={{ color: 'var(--text-secondary)' }}>Industrial Knowledge Intelligence Platform</p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>
            <span className="status-dot status-success animate-pulse"></span>
            System Online
          </span>
          <button className="btn-secondary">Settings</button>
        </div>
      </header>

      <div className="grid-2">
        {/* Left Column: Expert Knowledge Copilot */}
        <section className="glass-panel" style={{ display: 'flex', flexDirection: 'column', height: '70vh' }}>
          <h2>Expert Knowledge Copilot</h2>
          
          {/* Chat History Area */}
          <div style={{ flex: 1, overflowY: 'auto', padding: '1rem 0', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{ alignSelf: 'flex-start', background: 'rgba(255,255,255,0.05)', padding: '1rem', borderRadius: 'var(--radius-md)', maxWidth: '85%' }}>
              <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Operator (10:42 AM)</p>
              <p>Why is Pump P-102 overheating and vibrating so much?</p>
            </div>
            
            <div style={{ alignSelf: 'flex-end', background: 'rgba(0,240,255,0.1)', border: '1px solid var(--glass-border)', padding: '1rem', borderRadius: 'var(--radius-md)', maxWidth: '85%' }}>
              <p style={{ fontSize: '0.9rem', color: 'var(--accent-cyan)', marginBottom: '0.5rem', display: 'flex', justifyContent: 'space-between' }}>
                <span>Root Cause Analysis Agent</span>
                <span style={{ color: 'var(--accent-success)' }}>98% Confidence</span>
              </p>
              <p style={{ marginBottom: '1rem' }}>Based on the SOP and historical maintenance logs, it is highly probable the shaft has come out of alignment. I have drafted a Work Order for inspection.</p>
              
              {/* Citation Badges */}
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '0.75rem', background: 'rgba(255,255,255,0.1)', padding: '0.2rem 0.5rem', borderRadius: '4px' }}>📄 SOP: P-102 Manual (Page 2)</span>
                <span style={{ fontSize: '0.75rem', background: 'rgba(255,255,255,0.1)', padding: '0.2rem 0.5rem', borderRadius: '4px' }}>🔗 Graph: Event EVT-2026-001</span>
              </div>
            </div>
          </div>

          {/* Input Area */}
          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1rem' }}>
            <input 
              type="text" 
              placeholder="Ask the platform..." 
              style={{ flex: 1, background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', color: 'white', padding: '0.75rem', borderRadius: 'var(--radius-sm)', outline: 'none' }}
            />
            <button className="btn-primary">Send</button>
          </div>
        </section>

        {/* Right Column: Supervisor Action Dashboard */}
        <section className="glass-panel" style={{ display: 'flex', flexDirection: 'column' }}>
          <h2>Supervisor Action Dashboard</h2>
          <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>Human-in-the-loop pending approvals</p>
          
          <div style={{ background: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)', padding: '1.5rem', borderRadius: 'var(--radius-md)', position: 'relative' }}>
            <div style={{ position: 'absolute', top: '1rem', right: '1rem' }}>
              <span className="status-dot status-warning animate-pulse"></span>
              <span style={{ fontSize: '0.8rem', color: 'var(--accent-warning)' }}>Pending Review</span>
            </div>
            
            <h3 style={{ fontSize: '1.1rem', color: 'var(--accent-warning)' }}>Draft: SAP Work Order</h3>
            <div style={{ display: 'grid', gridTemplateColumns: '100px 1fr', gap: '0.5rem', margin: '1rem 0', fontSize: '0.9rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>Asset:</span><span>Centrifugal Pump (P-102)</span>
              <span style={{ color: 'var(--text-muted)' }}>Action:</span><span>Inspect & Realign Drive End Bearing</span>
              <span style={{ color: 'var(--text-muted)' }}>Priority:</span><span style={{ color: 'var(--accent-critical)' }}>CRITICAL</span>
              <span style={{ color: 'var(--text-muted)' }}>Generated By:</span><span>RCA Agent Swarm</span>
            </div>
            
            <div style={{ display: 'flex', gap: '1rem', marginTop: '1.5rem' }}>
              <button className="btn-primary" style={{ flex: 1 }}>Approve & Execute</button>
              <button className="btn-secondary" style={{ flex: 1, borderColor: 'var(--accent-critical)', color: 'var(--accent-critical)' }}>Reject (Evolve Knowledge)</button>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
